language: node_js
node_js:
- '8'
install: npm install
before_script:
- npm install -g gulp-cli
script: gulp test
deploy:
  skip_cleanup: true
  provider: script
  script: ./deployToWebStore.sh
  on:
    branch:
      - develop
      - master
env:
  CLIENT_ID=405889148522-dbeip54l7acipb7ruq5f964srqom9qqo.apps.googleusercontent.com
  APP_ID=emeajcjikgmcekalbihnnjlbpeaipjjn
