language: node_js
node_js:
- '8'
install: npm install
before_script:
- npm install -g gulp-cli
script: gulp test
deploy:
  skip_cleanup: true
  provider: script
  script: ./deployToWebStore.sh
  on:
    branch: develop
env:
  CLIENT_ID=405889148522-dvlql2ojksd68hk58cil0hc92f1bto8g.apps.googleusercontent.com
  APP_ID=ndfeidokhhlghgiccjolgigajeomjjom
